server:
  port: 8050

spring:
  application:
    name: zipkin-server

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:pass@server1:8100/eureka,http://user:pass@server2:8200/eureka